spring.application.name=ITP_PP1_JwtDemo
server.port=8088
jwt.secret=viratkohli_viratkohli_viratkohli_123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Wipro@123
spring.datasource.url=jdbc:postgresql://localhost:5432/ppp1springbootdb-dev